<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20190504144952.2"
expanded="leo.20190504145550.1,leo.20190504145550.22,leo.20190504145550.23,leo.20190504145550.24,leo.20190504145550.25,leo.20190504145550.26,leo.20190504145550.27,"><vh>@auto index.html</vh></v>
</vnodes>
<tnodes>
</tnodes>
</leo_file>
